### PR TITLE
Copy composer json and lock

### LINKED ISSUE #95: Composer.json missing?
I might be missing something here so feel free to correct me, but I do not understand why composer is installed but Mautic composer.json and composer.lock are not added to the container.

What's point of having composer without the project's project file ?
I know those files are not present in the archive which is downloaded but I mostly wonder if there is a reason for not adding them or if it's a mistake that should be fixed.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://app.bountysource.com/issues/72358479-composer-json-missing?utm_campaign=plugin&utm_content=tracker%2F20392502&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://app.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F20392502&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Copy composer json and lock to fix #95

### CODE REVIEW

**Comment by madmath03** [comment]
@luizeof I've also updated this PR with the master branch.

For info, if this gets accepted, I also have a related enhancement PR to allow automatic install of plugins: https://github.com/Monogramm/docker-mautic-base/tree/feature/plugins

**Comment by luizeof** [comment]
found this error: 

`/entrypoint.sh: line 76: [: too many arguments,
Mautic not found in /var/www/html - copying now...,
Copying Mautic composer config now...,
cp: cannot stat '/usr/src/mautic-src/mautic-2.15.2/composer.json': No such file or directory`

can you test please?

**Comment by madmath03** [comment]
@luizeof That's weird... so far, I'm not able to reproduce the issue you mentioned, either manually or through Travis-CI.

Would you consider to merge #93 first so that we can (maybe) more easily test this ?

**Comment by dmitryuk** [comment]
Hello, any plans to continue work on PR? The same problem

**Comment by RCheesley** [comment]
Hi folks, I believe that this was fixed in Core, sorry that it wasn't reviewed here sooner. I'll close this PR down but feel free to reply if it's still relevant.

**Pull request closed without merging**
