### PR TITLE
Add PHP.ini setup to fix #78 & fix #69

### LINKED ISSUE #69: How to set PHP date.timezone setting?
The first time I accessed mautic, the installer recommended the following

> The date.timezone setting is not set in your PHP configuration. Mautic has set the default timezone to 'UTC' but we suggest setting this in your PHP configuration.

I looked for an environment variable or something, but didn't find anything. Is there some way to control the timezone?

### LINKED ISSUE #78: PHP Memory limit is set to 135 by default only
The memory limit should be increased by default, as a PHP memory limit with 135MB is a cause for many errors.

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Add PHP.ini setup to fix #78 & fix #69
* Instead of copying sample php.ini file, generate one inside entrypoint
* Initialize php.ini with env variables

### CODE REVIEW

**Comment by luizeof** [comment]
Thanks !!!! testing ...

**Comment by madmath03** [comment]
You're welcome ;)
I've opened several issues and PR in those last few days, so feel free to ask any questions if you need more explanations on them.

**Comment by RafaelAybar** [comment]
@luizeof Hi, any notice about this?

**Comment by luizeof** [comment]
@madmath03

Hello, how are you? sorry for the delay. Due to the moves between Mautic / Aquia there was some delay in communication between the mautic team and me about the permissions on the dockerhub and github repository.

Now the problem is solved and I will come back with the pulls and issues.

Could you please update your pull with the latest version of the master? just to avoid merge problems.

Thank you!

**Comment by madmath03** [comment]
@luizeof Sure. Should be good now.

Glad to see you back here :+1: 
I hope you will also find the time to look at PR on the main project, like mautic/mautic/pull/7395 😛 

Let me know if you need anything else.

**Comment by luizeof** [comment]
tested and works! thanks @madmath03

**Pull request merged**
