### PR TITLE
Bump 2.14.0

### PR DESCRIPTION
**Pull request by luizeof**

### CODE REVIEW

**Comment by daniel-kossakowski-droptica** [comment]
Any update about this?

**Comment by collinkrawll** [comment]
Just posting some feedback here. I was able to get this to work but I had to make a couple of additional changes. 

I started with this PR and then also applied the changes from [61](https://github.com/mautic/docker-mautic/pull/61).

Then, I also changed the mautic download line in the Dockerfile from:

```
RUN curl -o mautic.zip -SL https://s3.amazonaws.com/mautic/releases/${MAUTIC_VERSION}.zip \
```
to
```
RUN curl -o mautic.zip -SL https://github.com/mautic/mautic/releases/download/${MAUTIC_VERSION}/${MAUTIC_VERSION}.zip \
```
It seems that 2.14.0 isn't on s3 for some reason.

After those changes the docker build for 2.14.0 worked.

**Comment by luizeof** [comment]
@collinkrawll 
was testing and did not really identify this problem. I'll test that right now.

Thank you very much

**Comment by luizeof** [comment]
@collinkrawll can you test this pull please?

**Comment by collinkrawll** [comment]
It works. Thanks @luizeof

**Pull request merged**
