### PR TITLE
Release 5.0.0 rc1

### PR DESCRIPTION
**Pull request by redtux**
- Bump Mautic version from 2.16.2 to 5.0.0-rc1
- Ignore files copied from 'common/'

### CODE REVIEW

**Comment by redtux** [comment]
Closes [#245](https://github.com/mautic/docker-mautic/issues/245)

**Comment by mollux** [comment]
@redtux thaks for the PR! 

For M5 we did a full overhaul of the Mautic images, to make them more in line with current best practices.

Please see #238 as background, and https://hub.docker.com/r/mautic/mautic for the new images.

I'm closing this PR as such

**Comment by redtux** [comment]
🤩 Great, thank you for the update! 👍

Although it's well explained in the docs, my "issue" was that I might not have fully understood the versioning, where the "latest" tag did not point to the latest version, and I also had missed that there already was a similar PR before for Mautic 5.

To publish the images on Docker Hub I ended up forking the repo (and changing the update script a bit to use env vars and docker compose), which fortunately isn't needed anymore. 

Btw you might consider using a simple docker compose file like here. https://github.com/redtux/docker-mautic/blob/main/common/compose.yaml

In any case, I am glad you fixed this, and that we can keep using the official images also for Mautic 5.

Thank you all for the great work, and for the kind community! 🎉

**Comment by redtux** [comment]
🤩 Great, thank you for the update! 👍

Although it's well explained in the docs, my "issue" was that I might not have fully understood the versioning, where the "latest" tag did not point to the latest version, and I also had missed that there already was a similar PR before for Mautic 5.

To publish the images on Docker Hub I ended up forking the repo (and changing the update script a bit to use env vars and docker compose), which fortunately isn't needed anymore. 

~~Btw you might consider using a simple docker compose file like here. https://github.com/redtux/docker-mautic/blob/main/common/compose.yaml~~
Edit: Okay, it's in examples. 👌

In any case, I am glad you fixed this, and that we can keep using the official images also for Mautic 5.

Thank you all for the great work, and for the kind community! 🎉

**Comment by mollux** [comment]
@redtux if you have any suggestions to enhance the images, please do so via a separate PR or issue to discuss those.

**Pull request closed without merging**
