### PR TITLE
Common files cleanup and environment variable configuration rework

### PR DESCRIPTION
**Pull request by thinkl33t**
An effort has been made in the past to combine any dockerfiles into a 
central location, but wasn't finalized (i assume due to docker not 
allowing includes from directories higher up).

This completes this work, and documents how to run the Dockerfiles to 
produce working containers.

Additionally, this MR changes the environment variable config so that any environment 
variable changes are re-applied to local.php on container startup.  It 
is part of some work I am doing to help make the mautic containers more 
devops friendly.

### CODE REVIEW

**Comment by thinkl33t** [comment]
CLA should be signed - @cla-bot check

**Comment by RCheesley** [comment]
@cla-bot check 

Sorry this is a manual process @thinkl33t so it takes a bit of time before one of us adds signatories to the list :)

Done now!

**Comment by RCheesley** [comment]
Thank you for making the PR @thinkl33t - have requested a review from the core team and @luizeof who maintains the Docker image at present!

**Comment by thinkl33t** [comment]
Closing this as it is obsolete as of #196

**Pull request closed without merging**
