### PR TITLE
enable ssl connection for db in apache docker

### PR DESCRIPTION
**Pull request by jbouzekri**
I am not sure if you are interested in merging this. In the cloud most of the managed database have SSL enabled per default so it is mandatory to be able to setup ssl options in the db connection. I chose to not change the mautic base code to add this.

### CODE REVIEW

**Comment by jbouzekri** [comment]
Does not work because of the installer step. Is this step mandatory ? Can the installer be skipped as we provide database connection settings in env variable and it generates a simple `app/config/local.php` ?

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by luizeof** [comment]
@jbouzekri thanks for contribution ;)

please, use mautic3 branch ;)

**Comment by jbouzekri** [comment]
I am closing it as I am not using mautic anymore.

**Pull request closed without merging**
