### PR TITLE
Update to v2.4.0

### PR DESCRIPTION
**Pull request by roderickm**
Updates to version 2.4.0, moves shared files to common directory,
and incorporates the changes from the following issues and PRs:
* #4 & #9 - Mimic cron behavior with while loops in the entrypoint
  scripts, enabled by adding `MAUTIC_RUN_CRON_JOBS` environment
  variable. (Contrast with supervisord+cron method of #6 & #8)
* #11 - Add `php.ini` files as [suggested by the base
  image](https://hub.docker.com/_/php/) to enable the php directive
  `always_populate_raw_post_data` instead of a convoluted tar/sed method
  that breaks with each base image version update
* #12 - Similar to this rollup of other issues/PRs, but update to v2.4.0
* #14 - Add `-p` flag to mkdir to avoid failing when dir already exists
* #15 - Add `docker-php-ext-install zip` to Dockerfile, while-style cron

### CODE REVIEW

**Comment by joomlacorner** [comment]
@mbabker please recheck and merge to this branch.

**Comment by mbabker** [comment]
I'm not involved with this repository nor project anymore, please ping another administrator.

**Comment by jtraulle** [comment]
I'm also interested in this :smile: 

Maybe @dbhurley or @dongilbert can review that :wink:

**Comment by Gregy** [comment]
Thank you very much for this pull request. I am sorry I won't use most of it. I decided to include cron and run the jobs using a crontab file. It seems cleaner and more manageable. Also I flipped the logic so cron jobs are enabled by default (I think most users will want them).

**Pull request closed without merging**
