### PR TITLE
Add option to setting Timezone with ENV

### PR DESCRIPTION
**Pull request by luizeof**

### CODE REVIEW

**Comment by Gregy** [comment]
Hi, thank you for your contribution. Could you please tell me what do you use this code for? I cannot see the benefit.

**Comment by luizeof** [comment]
Here on Brazil we have daylight saving time from october to february .. on this period Mautic do not understand the hour from contact page hit, etc. Updating the system timezone fix this error.

**Comment by Gregy** [comment]
Setting the timezone in mautic settings did not work?

Configuration -> system settings -> system defaults -> default timezone

**Comment by luizeof** [comment]
@Gregy unfortunely not, but there are an issue https://github.com/mautic/mautic/issues/4221

**Pull request closed without merging**
