### PR TITLE
now builds mautic v3.1.1

### PR DESCRIPTION
**Pull request by nljms**

### CODE REVIEW

**Comment by RCheesley** [comment]
@godmode97 thanks for the PR - can you please sign the contributors agreement above?

**Comment by luizeof** [comment]
Testing your PR ;)

**Comment by luizeof** [comment]
@godmode97 did you signed the  contributors agreement  ?

**Comment by godmode97** [comment]
not yet, will sign it up later

**Comment by godmode97** [comment]
already signed the contributor license agreement

**Comment by RCheesley** [comment]
@cla-bot check

**Comment by dmitryuk** [comment]
Hello, any plans to accept the PR?

**Comment by RCheesley** [comment]
Hi folks, as Mautic 3 is no longer supported I'm going to go ahead and close this PR. Huge apologies that nobody got around to reviewing and merging the PR sooner.

**Pull request closed without merging**
